import { AssociationRule, AnalysisResults } from '../types';

export function triggerDownload(content: string, filename: string, mimeType: string = 'text/plain') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportRulesToCSV(rules: AssociationRule[], filename: string = 'association_rules.csv') {
  const headers = ['ID', 'Antecedent', 'Consequent', 'Support', 'Confidence', 'Lift', 'Leverage', 'Conviction', 'Count', 'Category'];
  const rows = rules.map((r) => [
    r.id,
    `"${r.antecedent.join(', ')}"`,
    `"${r.consequent.join(', ')}"`,
    (r.support * 100).toFixed(2) + '%',
    (r.confidence * 100).toFixed(2) + '%',
    r.lift.toFixed(3),
    r.leverage.toFixed(4),
    r.conviction.toFixed(2),
    r.transactionCount,
    `"${r.category || 'General'}"`,
  ]);

  const csvContent = [headers.join(','), ...rows.map((row) => row.join(','))].join('\n');
  triggerDownload(csvContent, filename, 'text/csv;charset=utf-8;');
}

export function exportRulesToJSON(rules: AssociationRule[], filename: string = 'association_rules.json') {
  const jsonContent = JSON.stringify(rules, null, 2);
  triggerDownload(jsonContent, filename, 'application/json');
}

export function exportAnalysisSummaryReport(analysis: AnalysisResults, filename: string = 'mba_executive_summary.txt') {
  const content = `================================================================================
MARKET BASKET INTELLIGENCE - EXECUTIVE SUMMARY REPORT
================================================================================
Run Date: ${new Date(analysis.timestamp).toLocaleString()}
Dataset: ${analysis.datasetName}
Algorithm: ${analysis.algorithmUsed.toUpperCase()}
Execution Time: ${analysis.executionTimeMs} ms

KEY PERFORMANCE INDICATORS:
--------------------------------------------------------------------------------
• Total Analyzed Transactions: ${analysis.totalTransactions.toLocaleString()}
• Unique Catalog Products:     ${analysis.uniqueProductsCount.toLocaleString()}
• Frequent Itemsets Uncovered: ${analysis.frequentItemsetsCount.toLocaleString()}
• Discovered Association Rules:${analysis.rulesCount.toLocaleString()}
• Average Rule Support:        ${(analysis.avgSupport * 100).toFixed(2)}%
• Average Rule Confidence:     ${(analysis.avgConfidence * 100).toFixed(2)}%
• Average Lift Factor:         ${analysis.avgLift.toFixed(2)}x

TOP HIGH-AFFINITY PRODUCT RULES:
--------------------------------------------------------------------------------
${analysis.rules
  .slice(0, 10)
  .map(
    (r, i) =>
      `${i + 1}. [${r.antecedent.join(', ')}]  ==>  [${r.consequent.join(', ')}]
   Support: ${(r.support * 100).toFixed(1)}% | Confidence: ${(r.confidence * 100).toFixed(1)}% | Lift: ${r.lift.toFixed(2)}x
   Insight: ${r.explanation}
   Action:  ${r.crossSellAction}
`
  )
  .join('\n')}

TOP CO-PURCHASED PRODUCT PAIRS:
--------------------------------------------------------------------------------
${analysis.topPairs
  .slice(0, 8)
  .map((p, i) => `${i + 1}. ${p.pair}: ${p.cooccurrences.toLocaleString()} transactions (Lift: ${p.lift.toFixed(2)}x)`)
  .join('\n')}

================================================================================
Generated by Market Basket Intelligence Platform
================================================================================`;

  triggerDownload(content, filename, 'text/plain;charset=utf-8;');
}

